Add views
butlermuwo/blog-app pull request #5
Opened 2022-05-10 19:00 UTC by butlermuwo

## Blog App Views 
In this pull request I did the following:
- Implemented the design from the sneak peek wireframes.
- Used methods that I created in processing data in models task(pull request).
- In order to display more posts & comments, I added some data to my database.

2022-05-10 20:03 UTC, Lameck1 requested changes
Hi, @butlermuwo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 20:03 UTC, Lameck1 commented on app/views/users/show.html.erb
> +        <h3><%= link_to post.title, user_posts_path(post.author_id) %></h3>
- [ ] Clicking on a single post should take us to that single post in the posts/show. Right now this is not the case, clicking on any post takes us to view all posts. Please consider refactoring like this:

  ```suggestion
        <h3><%= link_to post.title, user_post_path(post) %></h3>
  ```

2022-05-10 20:03 UTC, Lameck1 commented on app/views/users/show.html.erb
> +<% end %>
- [ ] After displaying the three most recent posts, a user should be able to see a button with the name `See all posts`. Now, this where we should add a link to the path that shows all users posts.

  Please add this button and make it link to all user's posts. This is as suggested in the design section below:
  
  
  ![image](https://user-images.githubusercontent.com/45002654/167707870-9008f923-f3df-4bde-b30d-5ae0275b01aa.png)

2022-05-10 20:03 UTC, Lameck1 commented on app/views/posts/index.html.erb
> +<%end%>
- [ ] When we render a post, we should also render the five most recent comments of that post. That is suggested by this section of the wireframe 👇🏼:

  ![image](https://user-images.githubusercontent.com/45002654/167712269-068710cf-ead5-470a-9537-f86c71d4b836.png)
  
  Please add code that will display the five most recent comments in this view.

2022-05-11 14:18 UTC, butlermuwo commented on app/views/users/show.html.erb
> +        <h3><%= link_to post.title, user_posts_path(post.author_id) %></h3>
Thanks @Lameck1 done.

2022-05-11 14:18 UTC, butlermuwo commented on app/views/users/show.html.erb
> +<% end %>
Thanks @Lameck1  Done.

2022-05-11 14:18 UTC, butlermuwo commented on app/views/posts/index.html.erb
> +<%end%>
Thanks @Lameck1 done.

2022-05-11 15:14 UTC, rustam-tolipov approved these changes
## Hi @butlermuwo 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-11 15:35 UTC, butlermuwo commented
Cheers!😊 @Rustamxon7

2022-05-11 15:35 UTC, merged